//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmployeeResourcesUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmployeeResourcesUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp.Areas.Employees.Views.App_LocalResources.EmployeeResourcesUI", typeof(EmployeeResourcesUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Letters.
        /// </summary>
        public static string btnReceivedLetters {
            get {
                return ResourceManager.GetString("btnReceivedLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent Letters.
        /// </summary>
        public static string btnSentLetters {
            get {
                return ResourceManager.GetString("btnSentLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string lblAccept {
            get {
                return ResourceManager.GetString("lblAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string lblAction {
            get {
                return ResourceManager.GetString("lblAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string lblAddNew {
            get {
                return ResourceManager.GetString("lblAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string lblApprove {
            get {
                return ResourceManager.GetString("lblApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Requests.
        /// </summary>
        public static string lblApprovedRequest {
            get {
                return ResourceManager.GetString("lblApprovedRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string lblAttachment {
            get {
                return ResourceManager.GetString("lblAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Balance.
        /// </summary>
        public static string lblAvailableBalance {
            get {
                return ResourceManager.GetString("lblAvailableBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string lblBody {
            get {
                return ResourceManager.GetString("lblBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkin Date.
        /// </summary>
        public static string lblCheckInDate {
            get {
                return ResourceManager.GetString("lblCheckInDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time In.
        /// </summary>
        public static string lblCheckinTime {
            get {
                return ResourceManager.GetString("lblCheckinTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Out.
        /// </summary>
        public static string lblCheckoutTime {
            get {
                return ResourceManager.GetString("lblCheckoutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string lblComment {
            get {
                return ResourceManager.GetString("lblComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string lblDate {
            get {
                return ResourceManager.GetString("lblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time.
        /// </summary>
        public static string lblDateTime {
            get {
                return ResourceManager.GetString("lblDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string lblDecline {
            get {
                return ResourceManager.GetString("lblDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string lblDepartment {
            get {
                return ResourceManager.GetString("lblDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name.
        /// </summary>
        public static string lblDepartmentName {
            get {
                return ResourceManager.GetString("lblDepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emp #.
        /// </summary>
        public static string lblemail {
            get {
                return ResourceManager.GetString("lblemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string lblEmployeeName {
            get {
                return ResourceManager.GetString("lblEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees Cancel Leave Request(s).
        /// </summary>
        public static string lblEmployeesCancelLeaveRequest {
            get {
                return ResourceManager.GetString("lblEmployeesCancelLeaveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees Cash In Leave Request(s).
        /// </summary>
        public static string lblEmployeesCashInLeave {
            get {
                return ResourceManager.GetString("lblEmployeesCashInLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees Leave Request(s).
        /// </summary>
        public static string lblEmployeesleaveRequest {
            get {
                return ResourceManager.GetString("lblEmployeesleaveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees Official Letter Request(s).
        /// </summary>
        public static string lblEmployeesOfficialLetterRequests {
            get {
                return ResourceManager.GetString("lblEmployeesOfficialLetterRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees Permission Leave Request(s).
        /// </summary>
        public static string lblEmployeesPermissionLeaveRequests {
            get {
                return ResourceManager.GetString("lblEmployeesPermissionLeaveRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees Short Leave Requests.
        /// </summary>
        public static string lblEmployeesShortLeaveRequests {
            get {
                return ResourceManager.GetString("lblEmployeesShortLeaveRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First select records from grid.
        /// </summary>
        public static string lblFristSelectRecordFromGrid {
            get {
                return ResourceManager.GetString("lblFristSelectRecordFromGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Name.
        /// </summary>
        public static string lblLeaveName {
            get {
                return ResourceManager.GetString("lblLeaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Type.
        /// </summary>
        public static string lblLeaveType {
            get {
                return ResourceManager.GetString("lblLeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter Number.
        /// </summary>
        public static string lblLetterNumber {
            get {
                return ResourceManager.GetString("lblLetterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter Type.
        /// </summary>
        public static string lblLetterType {
            get {
                return ResourceManager.GetString("lblLetterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Read.
        /// </summary>
        public static string lblMarkAsRead {
            get {
                return ResourceManager.GetString("lblMarkAsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string lblNew {
            get {
                return ResourceManager.GetString("lblNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string lblNote {
            get {
                return ResourceManager.GetString("lblNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string lblNumberOfDays {
            get {
                return ResourceManager.GetString("lblNumberOfDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Hours.
        /// </summary>
        public static string lblNumberOfHours {
            get {
                return ResourceManager.GetString("lblNumberOfHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string lblOther {
            get {
                return ResourceManager.GetString("lblOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Requests.
        /// </summary>
        public static string lblPendingRequest {
            get {
                return ResourceManager.GetString("lblPendingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed.
        /// </summary>
        public static string lblProcessed {
            get {
                return ResourceManager.GetString("lblProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string lblRequest {
            get {
                return ResourceManager.GetString("lblRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date.
        /// </summary>
        public static string lblRequestDate {
            get {
                return ResourceManager.GetString("lblRequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Deny Comment.
        /// </summary>
        public static string lblRequestDenyComment {
            get {
                return ResourceManager.GetString("lblRequestDenyComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Time.
        /// </summary>
        public static string lblReturnTime {
            get {
                return ResourceManager.GetString("lblReturnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string lblSearch {
            get {
                return ResourceManager.GetString("lblSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        public static string lblShowAll {
            get {
                return ResourceManager.GetString("lblShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        public static string lblSignature {
            get {
                return ResourceManager.GetString("lblSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string lblSignOut {
            get {
                return ResourceManager.GetString("lblSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Status (Arabic).
        /// </summary>
        public static string lblSocialStatusArabic {
            get {
                return ResourceManager.GetString("lblSocialStatusArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Status (English).
        /// </summary>
        public static string lblSocialStatusEnglish {
            get {
                return ResourceManager.GetString("lblSocialStatusEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string lblStartDate {
            get {
                return ResourceManager.GetString("lblStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string lblStartTime {
            get {
                return ResourceManager.GetString("lblStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string lblSubject {
            get {
                return ResourceManager.GetString("lblSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Description.
        /// </summary>
        public static string lblTheDescription {
            get {
                return ResourceManager.GetString("lblTheDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment not found.
        /// </summary>
        public static string MsgAttachmentNotFound {
            get {
                return ResourceManager.GetString("MsgAttachmentNotFound", resourceCulture);
            }
        }
    }
}
