//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HumanResourceUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HumanResourceUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp.Areas.HumanResource.Views.App_LocalResources.HumanResourceUI", typeof(HumanResourceUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string btnGridAlreadyCreated {
            get {
                return ResourceManager.GetString("btnGridAlreadyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create .
        /// </summary>
        public static string btnGridCreateLogin {
            get {
                return ResourceManager.GetString("btnGridCreateLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string lblAction {
            get {
                return ResourceManager.GetString("lblAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash In Leiu.
        /// </summary>
        public static string lblCashInLieu {
            get {
                return ResourceManager.GetString("lblCashInLieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Name (English).
        /// </summary>
        public static string lblCertificateName {
            get {
                return ResourceManager.GetString("lblCertificateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Name (Arabic).
        /// </summary>
        public static string lblCertificateNameArb {
            get {
                return ResourceManager.GetString("lblCertificateNameArb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string lblClose {
            get {
                return ResourceManager.GetString("lblClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Document (English).
        /// </summary>
        public static string lblCompanyDocument {
            get {
                return ResourceManager.GetString("lblCompanyDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Type.
        /// </summary>
        public static string lblContractType {
            get {
                return ResourceManager.GetString("lblContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع العقد.
        /// </summary>
        public static string lblContractType1 {
            get {
                return ResourceManager.GetString("lblContractType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string lblCountry {
            get {
                return ResourceManager.GetString("lblCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User Login.
        /// </summary>
        public static string lblCreateUserLogin {
            get {
                return ResourceManager.GetString("lblCreateUserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree Name.
        /// </summary>
        public static string lblDegreeName {
            get {
                return ResourceManager.GetString("lblDegreeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Issue Date.
        /// </summary>
        public static string lblDegressIssueDate {
            get {
                return ResourceManager.GetString("lblDegressIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name.
        /// </summary>
        public static string lblDepartementName {
            get {
                return ResourceManager.GetString("lblDepartementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string lblDepartment {
            get {
                return ResourceManager.GetString("lblDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (English).
        /// </summary>
        public static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (Arabic).
        /// </summary>
        public static string lblDescriptionArb {
            get {
                return ResourceManager.GetString("lblDescriptionArb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (English).
        /// </summary>
        public static string lblDescriptionEng {
            get {
                return ResourceManager.GetString("lblDescriptionEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string lblEducationalDocument {
            get {
                return ResourceManager.GetString("lblEducationalDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree From Country.
        /// </summary>
        public static string lblEducationalDocumentDegreeFromCountry {
            get {
                return ResourceManager.GetString("lblEducationalDocumentDegreeFromCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree Marks (%).
        /// </summary>
        public static string lblEducationalDocumentDegreeMarks {
            get {
                return ResourceManager.GetString("lblEducationalDocumentDegreeMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree Name (Arabic).
        /// </summary>
        public static string lblEducationalDocumentDegreeNameArb {
            get {
                return ResourceManager.GetString("lblEducationalDocumentDegreeNameArb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree Name (English).
        /// </summary>
        public static string lblEducationalDocumentDegreeNameEng {
            get {
                return ResourceManager.GetString("lblEducationalDocumentDegreeNameEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institute Name (Arabic).
        /// </summary>
        public static string lblEducationalDocumentInstituteNameArb {
            get {
                return ResourceManager.GetString("lblEducationalDocumentInstituteNameArb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institute Name (English).
        /// </summary>
        public static string lblEducationalDocumentInstituteNameEng {
            get {
                return ResourceManager.GetString("lblEducationalDocumentInstituteNameEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree Issue Date.
        /// </summary>
        public static string lblEducationalDocumentIssueDate {
            get {
                return ResourceManager.GetString("lblEducationalDocumentIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emirates ID Number.
        /// </summary>
        public static string lblEID {
            get {
                return ResourceManager.GetString("lblEID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EID Number.
        /// </summary>
        public static string lblEIDNumber {
            get {
                return ResourceManager.GetString("lblEIDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emirates ID.
        /// </summary>
        public static string lblEmirates {
            get {
                return ResourceManager.GetString("lblEmirates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emirates Of Residency.
        /// </summary>
        public static string lblEmiratesOfResidency {
            get {
                return ResourceManager.GetString("lblEmiratesOfResidency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emirates Of Residency (Arabic).
        /// </summary>
        public static string lblEmiratesOfResidencyArb {
            get {
                return ResourceManager.GetString("lblEmiratesOfResidencyArb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emirates Of Residency (English).
        /// </summary>
        public static string lblEmiratesOfResidencyEng {
            get {
                return ResourceManager.GetString("lblEmiratesOfResidencyEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string lblEmployeeName {
            get {
                return ResourceManager.GetString("lblEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Number.
        /// </summary>
        public static string lblEmployeeNumber {
            get {
                return ResourceManager.GetString("lblEmployeeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment Status.
        /// </summary>
        public static string lblEmploymentStatus {
            get {
                return ResourceManager.GetString("lblEmploymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emp #.
        /// </summary>
        public static string lblEmpNum {
            get {
                return ResourceManager.GetString("lblEmpNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires In days.
        /// </summary>
        public static string lblExpiresIn {
            get {
                return ResourceManager.GetString("lblExpiresIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        public static string lblExpiryDate {
            get {
                return ResourceManager.GetString("lblExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string lblFile {
            get {
                return ResourceManager.GetString("lblFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Country.
        /// </summary>
        public static string lblFromCountry {
            get {
                return ResourceManager.GetString("lblFromCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institute Name.
        /// </summary>
        public static string lblIntituteName {
            get {
                return ResourceManager.GetString("lblIntituteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date.
        /// </summary>
        public static string lblIssueDate {
            get {
                return ResourceManager.GetString("lblIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining Date.
        /// </summary>
        public static string lblJoinDate {
            get {
                return ResourceManager.GetString("lblJoinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        public static string lblLeave {
            get {
                return ResourceManager.GetString("lblLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Balance.
        /// </summary>
        public static string lblLeavebalance {
            get {
                return ResourceManager.GetString("lblLeavebalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Cancellation .
        /// </summary>
        public static string lblLeaveCancellation {
            get {
                return ResourceManager.GetString("lblLeaveCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Type.
        /// </summary>
        public static string lblLeaveType {
            get {
                return ResourceManager.GetString("lblLeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Manager.
        /// </summary>
        public static string lblLineManager {
            get {
                return ResourceManager.GetString("lblLineManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string lblLogin {
            get {
                return ResourceManager.GetString("lblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks(%).
        /// </summary>
        public static string lblMarks {
            get {
                return ResourceManager.GetString("lblMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks%.
        /// </summary>
        public static string lblMarksPercentage {
            get {
                return ResourceManager.GetString("lblMarksPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality Card Expiry Date.
        /// </summary>
        public static string lblMunicipalityCardExpiryDate {
            get {
                return ResourceManager.GetString("lblMunicipalityCardExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality Card Issue Date.
        /// </summary>
        public static string lblMunicipalityCardIssueDate {
            get {
                return ResourceManager.GetString("lblMunicipalityCardIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality Card Number.
        /// </summary>
        public static string lblMunicipalityCardNumber {
            get {
                return ResourceManager.GetString("lblMunicipalityCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality Card Release Date.
        /// </summary>
        public static string lblMunicipalityCardReleaseDate {
            get {
                return ResourceManager.GetString("lblMunicipalityCardReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name  (Arabic).
        /// </summary>
        public static string lblNameArb {
            get {
                return ResourceManager.GetString("lblNameArb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (English).
        /// </summary>
        public static string lblNameEng {
            get {
                return ResourceManager.GetString("lblNameEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string lblNationality {
            get {
                return ResourceManager.GetString("lblNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password English.
        /// </summary>
        public static string lblNewPassword {
            get {
                return ResourceManager.GetString("lblNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        public static string lblOccupation {
            get {
                return ResourceManager.GetString("lblOccupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter.
        /// </summary>
        public static string lblOfficialLetter {
            get {
                return ResourceManager.GetString("lblOfficialLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password English.
        /// </summary>
        public static string lblOldPassword {
            get {
                return ResourceManager.GetString("lblOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Status (Arabic).
        /// </summary>
        public static string lblOtherStatusArb {
            get {
                return ResourceManager.GetString("lblOtherStatusArb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Status (English).
        /// </summary>
        public static string lblOtherStatusEng {
            get {
                return ResourceManager.GetString("lblOtherStatusEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Section.
        /// </summary>
        public static string lblParentDepartment {
            get {
                return ResourceManager.GetString("lblParentDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Department (Arabic).
        /// </summary>
        public static string lblParentDepartmentArb {
            get {
                return ResourceManager.GetString("lblParentDepartmentArb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Department (English).
        /// </summary>
        public static string lblParentDepartmentEng {
            get {
                return ResourceManager.GetString("lblParentDepartmentEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Expiry Date.
        /// </summary>
        public static string lblPassportExpiryDate {
            get {
                return ResourceManager.GetString("lblPassportExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Issue Date.
        /// </summary>
        public static string lblPassportIssueDate {
            get {
                return ResourceManager.GetString("lblPassportIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Number.
        /// </summary>
        public static string lblPassportNumber {
            get {
                return ResourceManager.GetString("lblPassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Release Date.
        /// </summary>
        public static string lblPassportReleaseDate {
            get {
                return ResourceManager.GetString("lblPassportReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string lblPersonalDocument {
            get {
                return ResourceManager.GetString("lblPersonalDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        public static string lblPersonalDocumentExpiryDate {
            get {
                return ResourceManager.GetString("lblPersonalDocumentExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string lblPersonalDocumentReleaseDate {
            get {
                return ResourceManager.GetString("lblPersonalDocumentReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        public static string lblPersonalDocumentType {
            get {
                return ResourceManager.GetString("lblPersonalDocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string lblPhone {
            get {
                return ResourceManager.GetString("lblPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        public static string lblProfession {
            get {
                return ResourceManager.GetString("lblProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Image.
        /// </summary>
        public static string lblProfileImage {
            get {
                return ResourceManager.GetString("lblProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string lblReleaseDate {
            get {
                return ResourceManager.GetString("lblReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string lblReset {
            get {
                return ResourceManager.GetString("lblReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string lblRole {
            get {
                return ResourceManager.GetString("lblRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string lblSalary {
            get {
                return ResourceManager.GetString("lblSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Leave.
        /// </summary>
        public static string lblShortLeave {
            get {
                return ResourceManager.GetString("lblShortLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Status (Arabic).
        /// </summary>
        public static string lblSocialStatusArb {
            get {
                return ResourceManager.GetString("lblSocialStatusArb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Status (English).
        /// </summary>
        public static string lblSocialStatusEng {
            get {
                return ResourceManager.GetString("lblSocialStatusEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Password .
        /// </summary>
        public static string lblUpdatePassword {
            get {
                return ResourceManager.GetString("lblUpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Expiry Date.
        /// </summary>
        public static string lblVisaExpiryDate {
            get {
                return ResourceManager.GetString("lblVisaExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Issue Date.
        /// </summary>
        public static string lblVisaIssueDate {
            get {
                return ResourceManager.GetString("lblVisaIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Release Date.
        /// </summary>
        public static string lblVisaReleaseDate {
            get {
                return ResourceManager.GetString("lblVisaReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsorship.
        /// </summary>
        public static string lblVisaSponsorship {
            get {
                return ResourceManager.GetString("lblVisaSponsorship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Near to expire document .
        /// </summary>
        public static string nearToExpireModalHeader {
            get {
                return ResourceManager.GetString("nearToExpireModalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational Document.
        /// </summary>
        public static string tabEducationalDocument {
            get {
                return ResourceManager.GetString("tabEducationalDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Document.
        /// </summary>
        public static string tabPersonalDocument {
            get {
                return ResourceManager.GetString("tabPersonalDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Info.
        /// </summary>
        public static string tabPersonalInfo {
            get {
                return ResourceManager.GetString("tabPersonalInfo", resourceCulture);
            }
        }
    }
}
