//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeesRequestResourceUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmployeesRequestResourceUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmployeesRequestResourceUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp.Areas.EmployeesRequest.Views.App_LocalResources.EmployeesRequestResourceUI" +
                            "", typeof(EmployeesRequestResourceUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string lblAction {
            get {
                return ResourceManager.GetString("lblAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Balance.
        /// </summary>
        public static string lblAvailableBalance {
            get {
                return ResourceManager.GetString("lblAvailableBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string lblBalance {
            get {
                return ResourceManager.GetString("lblBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string lblComment {
            get {
                return ResourceManager.GetString("lblComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment (Arabic).
        /// </summary>
        public static string lblCommentArb {
            get {
                return ResourceManager.GetString("lblCommentArb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment (English).
        /// </summary>
        public static string lblCommentEng {
            get {
                return ResourceManager.GetString("lblCommentEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ/الوقت.
        /// </summary>
        public static string lblDateTime {
            get {
                return ResourceManager.GetString("lblDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string lblDays {
            get {
                return ResourceManager.GetString("lblDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction Date.
        /// </summary>
        public static string lblDeductionDate {
            get {
                return ResourceManager.GetString("lblDeductionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees Leave Request(s).
        /// </summary>
        public static string lblEmployeesLeaveRequest {
            get {
                return ResourceManager.GetString("lblEmployeesLeaveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string lblHours {
            get {
                return ResourceManager.GetString("lblHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Name.
        /// </summary>
        public static string lblLeaveName {
            get {
                return ResourceManager.GetString("lblLeaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Type.
        /// </summary>
        public static string lblLeaveType {
            get {
                return ResourceManager.GetString("lblLeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter Type.
        /// </summary>
        public static string lblLetterType {
            get {
                return ResourceManager.GetString("lblLetterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string lblNote {
            get {
                return ResourceManager.GetString("lblNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Days.
        /// </summary>
        public static string lblNumberOfDays {
            get {
                return ResourceManager.GetString("lblNumberOfDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Hours.
        /// </summary>
        public static string lblNumberOfHours {
            get {
                return ResourceManager.GetString("lblNumberOfHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string lblOther {
            get {
                return ResourceManager.GetString("lblOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date.
        /// </summary>
        public static string lblRequestDate {
            get {
                return ResourceManager.GetString("lblRequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Deny Comment.
        /// </summary>
        public static string lblRequestDenyComment {
            get {
                return ResourceManager.GetString("lblRequestDenyComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Time.
        /// </summary>
        public static string lblReturnTime {
            get {
                return ResourceManager.GetString("lblReturnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string lblSelect {
            get {
                return ResourceManager.GetString("lblSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Leave.
        /// </summary>
        public static string lblSelectLeave {
            get {
                return ResourceManager.GetString("lblSelectLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string lblStartTime {
            get {
                return ResourceManager.GetString("lblStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taken Leave.
        /// </summary>
        public static string lblTakenLeave {
            get {
                return ResourceManager.GetString("lblTakenLeave", resourceCulture);
            }
        }
    }
}
