//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string btnProcess {
            get {
                return ResourceManager.GetString("btnProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string btnReset {
            get {
                return ResourceManager.GetString("btnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string btnSignIn {
            get {
                return ResourceManager.GetString("btnSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to approve these requests ?.
        /// </summary>
        internal static string doYouReallyWantToApproveTheseRequests {
            get {
                return ResourceManager.GetString("doYouReallyWantToApproveTheseRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to approve this request ?.
        /// </summary>
        internal static string doYouReallyWantToApproveThisRequest {
            get {
                return ResourceManager.GetString("doYouReallyWantToApproveThisRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to change status ?.
        /// </summary>
        internal static string doYouReallyWantToChangeStatus {
            get {
                return ResourceManager.GetString("doYouReallyWantToChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to decline these requests ?.
        /// </summary>
        internal static string doYouReallyWantToDeclineTheseRequests {
            get {
                return ResourceManager.GetString("doYouReallyWantToDeclineTheseRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to decline this request ?.
        /// </summary>
        internal static string doYouReallyWantToDeclineThisRequest {
            get {
                return ResourceManager.GetString("doYouReallyWantToDeclineThisRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this record ?.
        /// </summary>
        internal static string doYouReallyWantToDeleteThisRecord {
            get {
                return ResourceManager.GetString("doYouReallyWantToDeleteThisRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to start working on it ?.
        /// </summary>
        internal static string doYouReallyWantToStartWorkingOnIt {
            get {
                return ResourceManager.GetString("doYouReallyWantToStartWorkingOnIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to transfer this file ?.
        /// </summary>
        internal static string doYouReallyWantToTransferThisFile {
            get {
                return ResourceManager.GetString("doYouReallyWantToTransferThisFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string lblAccept {
            get {
                return ResourceManager.GetString("lblAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string lblAction {
            get {
                return ResourceManager.GetString("lblAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed format(s) are (png, jpg).
        /// </summary>
        internal static string lblAllowedFormatsArePngJpgOnly {
            get {
                return ResourceManager.GetString("lblAllowedFormatsArePngJpgOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed format(s) are (png, jpg,pdf).
        /// </summary>
        internal static string lblAllowedFormatsArePngJpgPdf {
            get {
                return ResourceManager.GetString("lblAllowedFormatsArePngJpgPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string lblApplication {
            get {
                return ResourceManager.GetString("lblApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string lblApplicationVersionNo {
            get {
                return ResourceManager.GetString("lblApplicationVersionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string lblApprove {
            get {
                return ResourceManager.GetString("lblApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve ?.
        /// </summary>
        internal static string lblApproveQuestion {
            get {
                return ResourceManager.GetString("lblApproveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure ?.
        /// </summary>
        internal static string lblAreYouSure {
            get {
                return ResourceManager.GetString("lblAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string lblClose {
            get {
                return ResourceManager.GetString("lblClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string lblCompanyDescription {
            get {
                return ResourceManager.GetString("lblCompanyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (Arabic).
        /// </summary>
        internal static string lblCompanyDescriptionArb {
            get {
                return ResourceManager.GetString("lblCompanyDescriptionArb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (English).
        /// </summary>
        internal static string lblCompanyDescriptionEng {
            get {
                return ResourceManager.GetString("lblCompanyDescriptionEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Document.
        /// </summary>
        internal static string lblCompanyDocument {
            get {
                return ResourceManager.GetString("lblCompanyDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lblCompanyName {
            get {
                return ResourceManager.GetString("lblCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (Arabic).
        /// </summary>
        internal static string lblCompanyNameArb {
            get {
                return ResourceManager.GetString("lblCompanyNameArb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (English).
        /// </summary>
        internal static string lblCompanyNameEng {
            get {
                return ResourceManager.GetString("lblCompanyNameEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string lblDay {
            get {
                return ResourceManager.GetString("lblDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        internal static string lblDecline {
            get {
                return ResourceManager.GetString("lblDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline ?.
        /// </summary>
        internal static string lblDeclineQuestion {
            get {
                return ResourceManager.GetString("lblDeclineQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string lblDelete {
            get {
                return ResourceManager.GetString("lblDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document/Attachment .
        /// </summary>
        internal static string lblDocumentAttachment {
            get {
                return ResourceManager.GetString("lblDocumentAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string lblEdit {
            get {
                return ResourceManager.GetString("lblEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string lblEndDate {
            get {
                return ResourceManager.GetString("lblEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        internal static string lblEndTime {
            get {
                return ResourceManager.GetString("lblEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        internal static string lblExpiryDate {
            get {
                return ResourceManager.GetString("lblExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour(s).
        /// </summary>
        internal static string lblHours {
            get {
                return ResourceManager.GetString("lblHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INMA INT.LLC.
        /// </summary>
        internal static string lblInma {
            get {
                return ResourceManager.GetString("lblInma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date.
        /// </summary>
        internal static string lblIssueDate {
            get {
                return ResourceManager.GetString("lblIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string lblLoading {
            get {
                return ResourceManager.GetString("lblLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute(s).
        /// </summary>
        internal static string lblMinutes {
            get {
                return ResourceManager.GetString("lblMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string lblNo {
            get {
                return ResourceManager.GetString("lblNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not started yet.
        /// </summary>
        internal static string lblNotStartedYet {
            get {
                return ResourceManager.GetString("lblNotStartedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops....
        /// </summary>
        internal static string lblOops {
            get {
                return ResourceManager.GetString("lblOops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact to system engineer, Thank you...!.
        /// </summary>
        internal static string lblPleaseContactToSystemEngineerThankyou {
            get {
                return ResourceManager.GetString("lblPleaseContactToSystemEngineerThankyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered By.
        /// </summary>
        internal static string lblPoweredBy {
            get {
                return ResourceManager.GetString("lblPoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string lblRemarks {
            get {
                return ResourceManager.GetString("lblRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string lblReset {
            get {
                return ResourceManager.GetString("lblReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second(s).
        /// </summary>
        internal static string lblSeconds {
            get {
                return ResourceManager.GetString("lblSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string lblStartDate {
            get {
                return ResourceManager.GetString("lblStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        internal static string lblStartTime {
            get {
                return ResourceManager.GetString("lblStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        internal static string lblStatusExpired {
            get {
                return ResourceManager.GetString("lblStatusExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        internal static string lblStatusValid {
            get {
                return ResourceManager.GetString("lblStatusValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XtremeSoft.
        /// </summary>
        internal static string lblXtremeSoft {
            get {
                return ResourceManager.GetString("lblXtremeSoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xtreme Software.
        /// </summary>
        internal static string lblXtremesSoftware {
            get {
                return ResourceManager.GetString("lblXtremesSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string lblYes {
            get {
                return ResourceManager.GetString("lblYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You dont have permission to access this application..!.
        /// </summary>
        internal static string lblYouDontHavePermissionToAccessThisApplication {
            get {
                return ResourceManager.GetString("lblYouDontHavePermissionToAccessThisApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        internal static string textAlign {
            get {
                return ResourceManager.GetString("textAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0px.
        /// </summary>
        internal static string treeViewPaddingLeft {
            get {
                return ResourceManager.GetString("treeViewPaddingLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
