//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRModuleUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HumanResourceUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HumanResourceUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp.App_GlobalResources.HumanResourceUI", typeof(HumanResourceUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees Area.
        /// </summary>
        public static string Below_are_employees {
            get {
                return ResourceManager.GetString("Below are employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Manager.
        /// </summary>
        public static string Below_are_user_management {
            get {
                return ResourceManager.GetString("Below are user management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string btnGridAlreadyCreated {
            get {
                return ResourceManager.GetString("btnGridAlreadyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create .
        /// </summary>
        public static string btnGridCreateLogin {
            get {
                return ResourceManager.GetString("btnGridCreateLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Letters.
        /// </summary>
        public static string btnReceivedLetters {
            get {
                return ResourceManager.GetString("btnReceivedLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent Letters.
        /// </summary>
        public static string btnSentLetters {
            get {
                return ResourceManager.GetString("btnSentLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string btnSignIn {
            get {
                return ResourceManager.GetString("btnSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not apply with available balance 0.
        /// </summary>
        public static string canNotApplyWithAvailableBalanceZero {
            get {
                return ResourceManager.GetString("canNotApplyWithAvailableBalanceZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Profile.
        /// </summary>
        public static string employeeProfile {
            get {
                return ResourceManager.GetString("employeeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date is required.
        /// </summary>
        public static string enddateisrequired {
            get {
                return ResourceManager.GetString("enddateisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First select records from grid.
        /// </summary>
        public static string firstselectrecordsfromgrid {
            get {
                return ResourceManager.GetString("firstselectrecordsfromgrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humran Resource.
        /// </summary>
        public static string Human_Resouce_Module_Below {
            get {
                return ResourceManager.GetString("Human Resouce Module Below", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability to Coach and Train.
        /// </summary>
        public static string lblAbilitytoCoachandTrain {
            get {
                return ResourceManager.GetString("lblAbilitytoCoachandTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability to Learn Skills.
        /// </summary>
        public static string lblAbilitytoLearnSkills {
            get {
                return ResourceManager.GetString("lblAbilitytoLearnSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability to Plan and Organize.
        /// </summary>
        public static string lblAbilitytoPlanandOrganize {
            get {
                return ResourceManager.GetString("lblAbilitytoPlanandOrganize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above Expectations.
        /// </summary>
        public static string lblAboveExpectations {
            get {
                return ResourceManager.GetString("lblAboveExpectations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absent.
        /// </summary>
        public static string lblAbsent {
            get {
                return ResourceManager.GetString("lblAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string lblAccept {
            get {
                return ResourceManager.GetString("lblAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achieve Goals.
        /// </summary>
        public static string lblAchieveGoals {
            get {
                return ResourceManager.GetString("lblAchieveGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledged.
        /// </summary>
        public static string lblAcknowledged {
            get {
                return ResourceManager.GetString("lblAcknowledged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string lblAction {
            get {
                return ResourceManager.GetString("lblAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string lblAddNew {
            get {
                return ResourceManager.GetString("lblAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string lblApprove {
            get {
                return ResourceManager.GetString("lblApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By.
        /// </summary>
        public static string lblApprovedBy {
            get {
                return ResourceManager.GetString("lblApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Requests.
        /// </summary>
        public static string lblApprovedRequest {
            get {
                return ResourceManager.GetString("lblApprovedRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string lblAttachment {
            get {
                return ResourceManager.GetString("lblAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Balance.
        /// </summary>
        public static string lblAvailableBalance {
            get {
                return ResourceManager.GetString("lblAvailableBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string lblBalance {
            get {
                return ResourceManager.GetString("lblBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavioral and Commitment.
        /// </summary>
        public static string lblBehavioralandCommitment {
            get {
                return ResourceManager.GetString("lblBehavioralandCommitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below Expectations.
        /// </summary>
        public static string lblBelowExpectations {
            get {
                return ResourceManager.GetString("lblBelowExpectations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string lblBody {
            get {
                return ResourceManager.GetString("lblBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break.
        /// </summary>
        public static string lblBreak {
            get {
                return ResourceManager.GetString("lblBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break In.
        /// </summary>
        public static string lblBreakIn {
            get {
                return ResourceManager.GetString("lblBreakIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break Out.
        /// </summary>
        public static string lblBreakOut {
            get {
                return ResourceManager.GetString("lblBreakOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Cancellation.
        /// </summary>
        public static string lblCancelLeaveRequest {
            get {
                return ResourceManager.GetString("lblCancelLeaveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career Achievements.
        /// </summary>
        public static string lblCareerAchievements {
            get {
                return ResourceManager.GetString("lblCareerAchievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash In Leiu.
        /// </summary>
        public static string lblCashInLieu {
            get {
                return ResourceManager.GetString("lblCashInLieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Name (English).
        /// </summary>
        public static string lblCertificateName {
            get {
                return ResourceManager.GetString("lblCertificateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Name (Arabic).
        /// </summary>
        public static string lblCertificateNameArb {
            get {
                return ResourceManager.GetString("lblCertificateNameArb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkin Date.
        /// </summary>
        public static string lblCheckInDate {
            get {
                return ResourceManager.GetString("lblCheckInDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time In.
        /// </summary>
        public static string lblCheckinTime {
            get {
                return ResourceManager.GetString("lblCheckinTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Out.
        /// </summary>
        public static string lblCheckoutTime {
            get {
                return ResourceManager.GetString("lblCheckoutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string lblClose {
            get {
                return ResourceManager.GetString("lblClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collaboration, Job Commitment and Attendance.
        /// </summary>
        public static string lblCollaborationJobCommitmentandAttendance {
            get {
                return ResourceManager.GetString("lblCollaborationJobCommitmentandAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string lblComment {
            get {
                return ResourceManager.GetString("lblComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment (Arabic).
        /// </summary>
        public static string lblCommentArb {
            get {
                return ResourceManager.GetString("lblCommentArb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment (English).
        /// </summary>
        public static string lblCommentEng {
            get {
                return ResourceManager.GetString("lblCommentEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string lblCompany {
            get {
                return ResourceManager.GetString("lblCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Document (English).
        /// </summary>
        public static string lblCompanyDocument {
            get {
                return ResourceManager.GetString("lblCompanyDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Manager.
        /// </summary>
        public static string lblCompanyManager {
            get {
                return ResourceManager.GetString("lblCompanyManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Rules.
        /// </summary>
        public static string lblCompanyRules {
            get {
                return ResourceManager.GetString("lblCompanyRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compliance with Rules of Procedure.
        /// </summary>
        public static string lblCompliancewithRulesofProcedure {
            get {
                return ResourceManager.GetString("lblCompliancewithRulesofProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Type.
        /// </summary>
        public static string lblContractType {
            get {
                return ResourceManager.GetString("lblContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooperation with Customers.
        /// </summary>
        public static string lblCooperationwithCustomers {
            get {
                return ResourceManager.GetString("lblCooperationwithCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string lblCountry {
            get {
                return ResourceManager.GetString("lblCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User Login.
        /// </summary>
        public static string lblCreateUserLogin {
            get {
                return ResourceManager.GetString("lblCreateUserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criterion.
        /// </summary>
        public static string lblCriterion {
            get {
                return ResourceManager.GetString("lblCriterion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Attendance.
        /// </summary>
        public static string lbldailyAttendance {
            get {
                return ResourceManager.GetString("lbldailyAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string lblDate {
            get {
                return ResourceManager.GetString("lblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/Time.
        /// </summary>
        public static string lblDateTime {
            get {
                return ResourceManager.GetString("lblDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string lblDays {
            get {
                return ResourceManager.GetString("lblDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline.
        /// </summary>
        public static string lblDecline {
            get {
                return ResourceManager.GetString("lblDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction Date.
        /// </summary>
        public static string lblDeductionDate {
            get {
                return ResourceManager.GetString("lblDeductionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree Name.
        /// </summary>
        public static string lblDegreeName {
            get {
                return ResourceManager.GetString("lblDegreeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Issue Date.
        /// </summary>
        public static string lblDegressIssueDate {
            get {
                return ResourceManager.GetString("lblDegressIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        public static string lblDelay {
            get {
                return ResourceManager.GetString("lblDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name.
        /// </summary>
        public static string lblDepartementName {
            get {
                return ResourceManager.GetString("lblDepartementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string lblDepartment {
            get {
                return ResourceManager.GetString("lblDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name.
        /// </summary>
        public static string lblDepartmentName {
            get {
                return ResourceManager.GetString("lblDepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (English).
        /// </summary>
        public static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (Arabic).
        /// </summary>
        public static string lblDescriptionArb {
            get {
                return ResourceManager.GetString("lblDescriptionArb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (English).
        /// </summary>
        public static string lblDescriptionEng {
            get {
                return ResourceManager.GetString("lblDescriptionEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development of his Performance.
        /// </summary>
        public static string lblDevelopmentofhisPerformance {
            get {
                return ResourceManager.GetString("lblDevelopmentofhisPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discipline in Attendance.
        /// </summary>
        public static string lblDisciplineinAttendance {
            get {
                return ResourceManager.GetString("lblDisciplineinAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string lblDocument {
            get {
                return ResourceManager.GetString("lblDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early.
        /// </summary>
        public static string lblEarly {
            get {
                return ResourceManager.GetString("lblEarly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early Out Time.
        /// </summary>
        public static string lblEarlyOutTime {
            get {
                return ResourceManager.GetString("lblEarlyOutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string lblEducationalDocument {
            get {
                return ResourceManager.GetString("lblEducationalDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree From Country.
        /// </summary>
        public static string lblEducationalDocumentDegreeFromCountry {
            get {
                return ResourceManager.GetString("lblEducationalDocumentDegreeFromCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree Marks (%).
        /// </summary>
        public static string lblEducationalDocumentDegreeMarks {
            get {
                return ResourceManager.GetString("lblEducationalDocumentDegreeMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree Name (Arabic).
        /// </summary>
        public static string lblEducationalDocumentDegreeNameArb {
            get {
                return ResourceManager.GetString("lblEducationalDocumentDegreeNameArb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree Name (English).
        /// </summary>
        public static string lblEducationalDocumentDegreeNameEng {
            get {
                return ResourceManager.GetString("lblEducationalDocumentDegreeNameEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institute Name (Arabic).
        /// </summary>
        public static string lblEducationalDocumentInstituteNameArb {
            get {
                return ResourceManager.GetString("lblEducationalDocumentInstituteNameArb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institute Name (English).
        /// </summary>
        public static string lblEducationalDocumentInstituteNameEng {
            get {
                return ResourceManager.GetString("lblEducationalDocumentInstituteNameEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree Issue Date.
        /// </summary>
        public static string lblEducationalDocumentIssueDate {
            get {
                return ResourceManager.GetString("lblEducationalDocumentIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emirates ID Number.
        /// </summary>
        public static string lblEID {
            get {
                return ResourceManager.GetString("lblEID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EID Number.
        /// </summary>
        public static string lblEIDNumber {
            get {
                return ResourceManager.GetString("lblEIDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emirates ID.
        /// </summary>
        public static string lblEmirates {
            get {
                return ResourceManager.GetString("lblEmirates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emirates Of Residency.
        /// </summary>
        public static string lblEmiratesOfResidency {
            get {
                return ResourceManager.GetString("lblEmiratesOfResidency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emirates Of Residency (Arabic).
        /// </summary>
        public static string lblEmiratesOfResidencyArb {
            get {
                return ResourceManager.GetString("lblEmiratesOfResidencyArb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emirates Of Residency (English).
        /// </summary>
        public static string lblEmiratesOfResidencyEng {
            get {
                return ResourceManager.GetString("lblEmiratesOfResidencyEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Document.
        /// </summary>
        public static string lblEmployeeDocument {
            get {
                return ResourceManager.GetString("lblEmployeeDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string lblEmployeeName {
            get {
                return ResourceManager.GetString("lblEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Number.
        /// </summary>
        public static string lblEmployeeNumber {
            get {
                return ResourceManager.GetString("lblEmployeeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Performance Evaluation.
        /// </summary>
        public static string lblEmployeePerformanceEvaluation {
            get {
                return ResourceManager.GetString("lblEmployeePerformanceEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string lblEmployees {
            get {
                return ResourceManager.GetString("lblEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees Attendance.
        /// </summary>
        public static string lblEmployeesAttendance {
            get {
                return ResourceManager.GetString("lblEmployeesAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees Cancel Leave Request(s).
        /// </summary>
        public static string lblEmployeesCancelLeaveRequest {
            get {
                return ResourceManager.GetString("lblEmployeesCancelLeaveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees Cash In Leave Request(s).
        /// </summary>
        public static string lblEmployeesCashInLeave {
            get {
                return ResourceManager.GetString("lblEmployeesCashInLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees Leave Request(s).
        /// </summary>
        public static string lblEmployeesleaveRequest {
            get {
                return ResourceManager.GetString("lblEmployeesleaveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees Link To Role.
        /// </summary>
        public static string lblEmployeesLinkToRole {
            get {
                return ResourceManager.GetString("lblEmployeesLinkToRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees Official Letter Request(s).
        /// </summary>
        public static string lblEmployeesOfficialLetterRequests {
            get {
                return ResourceManager.GetString("lblEmployeesOfficialLetterRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees Permission Leave Request(s).
        /// </summary>
        public static string lblEmployeesPermissionLeaveRequests {
            get {
                return ResourceManager.GetString("lblEmployeesPermissionLeaveRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees Short Leave Requests.
        /// </summary>
        public static string lblEmployeesShortLeaveRequests {
            get {
                return ResourceManager.GetString("lblEmployeesShortLeaveRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment Status.
        /// </summary>
        public static string lblEmploymentStatus {
            get {
                return ResourceManager.GetString("lblEmploymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emp #.
        /// </summary>
        public static string lblEmpNum {
            get {
                return ResourceManager.GetString("lblEmpNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation.
        /// </summary>
        public static string lblEvaluation {
            get {
                return ResourceManager.GetString("lblEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Request.
        /// </summary>
        public static string lblEvaluationRequest {
            get {
                return ResourceManager.GetString("lblEvaluationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluations.
        /// </summary>
        public static string lblEvaluations {
            get {
                return ResourceManager.GetString("lblEvaluations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evening.
        /// </summary>
        public static string lblEvening {
            get {
                return ResourceManager.GetString("lblEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceed Expections.
        /// </summary>
        public static string lblExceedExpections {
            get {
                return ResourceManager.GetString("lblExceedExpections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected.
        /// </summary>
        public static string lblExpected {
            get {
                return ResourceManager.GetString("lblExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires In days.
        /// </summary>
        public static string lblExpiresIn {
            get {
                return ResourceManager.GetString("lblExpiresIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        public static string lblExpiryDate {
            get {
                return ResourceManager.GetString("lblExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry date cannot be less than issue date.
        /// </summary>
        public static string lblExpiryDateCannotBeLessThanIssue {
            get {
                return ResourceManager.GetString("lblExpiryDateCannotBeLessThanIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string lblFile {
            get {
                return ResourceManager.GetString("lblFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flexibility in Getting the Job Done.
        /// </summary>
        public static string lblFlexibilityinGettingtheJobDone {
            get {
                return ResourceManager.GetString("lblFlexibilityinGettingtheJobDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string lblForward {
            get {
                return ResourceManager.GetString("lblForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First select records from grid.
        /// </summary>
        public static string lblFristSelectRecordFromGrid {
            get {
                return ResourceManager.GetString("lblFristSelectRecordFromGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string lblFrom {
            get {
                return ResourceManager.GetString("lblFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Country.
        /// </summary>
        public static string lblFromCountry {
            get {
                return ResourceManager.GetString("lblFromCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string lblHours {
            get {
                return ResourceManager.GetString("lblHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Benefit from the Experiences.
        /// </summary>
        public static string lblHowtoBenefitfromtheExperiences {
            get {
                return ResourceManager.GetString("lblHowtoBenefitfromtheExperiences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR.
        /// </summary>
        public static string lblHR {
            get {
                return ResourceManager.GetString("lblHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN.
        /// </summary>
        public static string lblIn {
            get {
                return ResourceManager.GetString("lblIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiative and Creativity.
        /// </summary>
        public static string lblInitiativeandCreativity {
            get {
                return ResourceManager.GetString("lblInitiativeandCreativity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiative or Method of Work.
        /// </summary>
        public static string lblInitiativeorMethodofWork {
            get {
                return ResourceManager.GetString("lblInitiativeorMethodofWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Letter.
        /// </summary>
        public static string lblInternalLetter {
            get {
                return ResourceManager.GetString("lblInternalLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institute Name.
        /// </summary>
        public static string lblIntituteName {
            get {
                return ResourceManager.GetString("lblIntituteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date.
        /// </summary>
        public static string lblIssueDate {
            get {
                return ResourceManager.GetString("lblIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Responsibilities.
        /// </summary>
        public static string lblJobResponsibilities {
            get {
                return ResourceManager.GetString("lblJobResponsibilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining Date.
        /// </summary>
        public static string lblJoinDate {
            get {
                return ResourceManager.GetString("lblJoinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late.
        /// </summary>
        public static string lblLate {
            get {
                return ResourceManager.GetString("lblLate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late In Time.
        /// </summary>
        public static string lblLateInTime {
            get {
                return ResourceManager.GetString("lblLateInTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning Ability.
        /// </summary>
        public static string lblLearningAbility {
            get {
                return ResourceManager.GetString("lblLearningAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        public static string lblLeave {
            get {
                return ResourceManager.GetString("lblLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Balance.
        /// </summary>
        public static string lblLeavebalance {
            get {
                return ResourceManager.GetString("lblLeavebalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave balance deduction details.
        /// </summary>
        public static string lblleavebalancedeductiondetails {
            get {
                return ResourceManager.GetString("lblleavebalancedeductiondetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Cancellation .
        /// </summary>
        public static string lblLeaveCancellation {
            get {
                return ResourceManager.GetString("lblLeaveCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Name.
        /// </summary>
        public static string lblLeaveName {
            get {
                return ResourceManager.GetString("lblLeaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Request.
        /// </summary>
        public static string lblLeaveRequest {
            get {
                return ResourceManager.GetString("lblLeaveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Type.
        /// </summary>
        public static string lblLeaveType {
            get {
                return ResourceManager.GetString("lblLeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter Number.
        /// </summary>
        public static string lblLetterNumber {
            get {
                return ResourceManager.GetString("lblLetterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter Request.
        /// </summary>
        public static string lblLetterRequest {
            get {
                return ResourceManager.GetString("lblLetterRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter Type.
        /// </summary>
        public static string lblLetterType {
            get {
                return ResourceManager.GetString("lblLetterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Manager.
        /// </summary>
        public static string lblLineManager {
            get {
                return ResourceManager.GetString("lblLineManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string lblLink {
            get {
                return ResourceManager.GetString("lblLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string lblLogin {
            get {
                return ResourceManager.GetString("lblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string lblLogout {
            get {
                return ResourceManager.GetString("lblLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Read.
        /// </summary>
        public static string lblMarkAsRead {
            get {
                return ResourceManager.GetString("lblMarkAsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks(%).
        /// </summary>
        public static string lblMarks {
            get {
                return ResourceManager.GetString("lblMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks%.
        /// </summary>
        public static string lblMarksPercentage {
            get {
                return ResourceManager.GetString("lblMarksPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning.
        /// </summary>
        public static string lblMorning {
            get {
                return ResourceManager.GetString("lblMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality Card Expiry Date.
        /// </summary>
        public static string lblMunicipalityCardExpiryDate {
            get {
                return ResourceManager.GetString("lblMunicipalityCardExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality Card Issue Date.
        /// </summary>
        public static string lblMunicipalityCardIssueDate {
            get {
                return ResourceManager.GetString("lblMunicipalityCardIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality Card Number.
        /// </summary>
        public static string lblMunicipalityCardNumber {
            get {
                return ResourceManager.GetString("lblMunicipalityCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality Card Release Date.
        /// </summary>
        public static string lblMunicipalityCardReleaseDate {
            get {
                return ResourceManager.GetString("lblMunicipalityCardReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name  (Arabic).
        /// </summary>
        public static string lblNameArb {
            get {
                return ResourceManager.GetString("lblNameArb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (English).
        /// </summary>
        public static string lblNameEng {
            get {
                return ResourceManager.GetString("lblNameEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string lblNationality {
            get {
                return ResourceManager.GetString("lblNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string lblNew {
            get {
                return ResourceManager.GetString("lblNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string lblNewBtn {
            get {
                return ResourceManager.GetString("lblNewBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string lblNewPassword {
            get {
                return ResourceManager.GetString("lblNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Signature.
        /// </summary>
        public static string lblNoSignature {
            get {
                return ResourceManager.GetString("lblNoSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string lblNote {
            get {
                return ResourceManager.GetString("lblNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Days.
        /// </summary>
        public static string lblNumberOfDays {
            get {
                return ResourceManager.GetString("lblNumberOfDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Hours.
        /// </summary>
        public static string lblNumberOfHours {
            get {
                return ResourceManager.GetString("lblNumberOfHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        public static string lblOccupation {
            get {
                return ResourceManager.GetString("lblOccupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter.
        /// </summary>
        public static string lblOfficialLetter {
            get {
                return ResourceManager.GetString("lblOfficialLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string lblOldPassword {
            get {
                return ResourceManager.GetString("lblOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string lblOther {
            get {
                return ResourceManager.GetString("lblOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Status (Arabic).
        /// </summary>
        public static string lblOtherStatusArb {
            get {
                return ResourceManager.GetString("lblOtherStatusArb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Status (English).
        /// </summary>
        public static string lblOtherStatusEng {
            get {
                return ResourceManager.GetString("lblOtherStatusEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUT.
        /// </summary>
        public static string lblOut {
            get {
                return ResourceManager.GetString("lblOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime.
        /// </summary>
        public static string lblOverTime {
            get {
                return ResourceManager.GetString("lblOverTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Section.
        /// </summary>
        public static string lblParentDepartment {
            get {
                return ResourceManager.GetString("lblParentDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Department (Arabic).
        /// </summary>
        public static string lblParentDepartmentArb {
            get {
                return ResourceManager.GetString("lblParentDepartmentArb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Department (English).
        /// </summary>
        public static string lblParentDepartmentEng {
            get {
                return ResourceManager.GetString("lblParentDepartmentEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Expiry Date.
        /// </summary>
        public static string lblPassportExpiryDate {
            get {
                return ResourceManager.GetString("lblPassportExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Issue Date.
        /// </summary>
        public static string lblPassportIssueDate {
            get {
                return ResourceManager.GetString("lblPassportIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Number.
        /// </summary>
        public static string lblPassportNumber {
            get {
                return ResourceManager.GetString("lblPassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Release Date.
        /// </summary>
        public static string lblPassportReleaseDate {
            get {
                return ResourceManager.GetString("lblPassportReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Requests.
        /// </summary>
        public static string lblPendingRequest {
            get {
                return ResourceManager.GetString("lblPendingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance and Achivment.
        /// </summary>
        public static string lblPerformanceandAchivment {
            get {
                return ResourceManager.GetString("lblPerformanceandAchivment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance,Productivity.
        /// </summary>
        public static string lblPerformanceProductivity {
            get {
                return ResourceManager.GetString("lblPerformanceProductivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Scores.
        /// </summary>
        public static string lblPerformanceScores {
            get {
                return ResourceManager.GetString("lblPerformanceScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Attendance.
        /// </summary>
        public static string lblPersonalAttendance {
            get {
                return ResourceManager.GetString("lblPersonalAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string lblPersonalDocument {
            get {
                return ResourceManager.GetString("lblPersonalDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        public static string lblPersonalDocumentExpiryDate {
            get {
                return ResourceManager.GetString("lblPersonalDocumentExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string lblPersonalDocumentReleaseDate {
            get {
                return ResourceManager.GetString("lblPersonalDocumentReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        public static string lblPersonalDocumentType {
            get {
                return ResourceManager.GetString("lblPersonalDocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string lblPhone {
            get {
                return ResourceManager.GetString("lblPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present.
        /// </summary>
        public static string lblPresent {
            get {
                return ResourceManager.GetString("lblPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedures.
        /// </summary>
        public static string lblProcedures {
            get {
                return ResourceManager.GetString("lblProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed.
        /// </summary>
        public static string lblProcessed {
            get {
                return ResourceManager.GetString("lblProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        public static string lblProfession {
            get {
                return ResourceManager.GetString("lblProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Image.
        /// </summary>
        public static string lblProfileImage {
            get {
                return ResourceManager.GetString("lblProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Holiday.
        /// </summary>
        public static string lblPublicHoliday {
            get {
                return ResourceManager.GetString("lblPublicHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Of Functionality.
        /// </summary>
        public static string lblQualityOfFunctionality {
            get {
                return ResourceManager.GetString("lblQualityOfFunctionality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratings.
        /// </summary>
        public static string lblRatings {
            get {
                return ResourceManager.GetString("lblRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Letter.
        /// </summary>
        public static string lblReadLetter {
            get {
                return ResourceManager.GetString("lblReadLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string lblReleaseDate {
            get {
                return ResourceManager.GetString("lblReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string lblremarks {
            get {
                return ResourceManager.GetString("lblremarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string lblReply {
            get {
                return ResourceManager.GetString("lblReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string lblRequest {
            get {
                return ResourceManager.GetString("lblRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Date.
        /// </summary>
        public static string lblRequestDate {
            get {
                return ResourceManager.GetString("lblRequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Deny Comment.
        /// </summary>
        public static string lblRequestDenyComment {
            get {
                return ResourceManager.GetString("lblRequestDenyComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string lblRequestExpired {
            get {
                return ResourceManager.GetString("lblRequestExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string lblRequestRunning {
            get {
                return ResourceManager.GetString("lblRequestRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        public static string lblRequestWaiting {
            get {
                return ResourceManager.GetString("lblRequestWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string lblReset {
            get {
                return ResourceManager.GetString("lblReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Time/To.
        /// </summary>
        public static string lblReturnTime {
            get {
                return ResourceManager.GetString("lblReturnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string lblRole {
            get {
                return ResourceManager.GetString("lblRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules List.
        /// </summary>
        public static string lblRulesList {
            get {
                return ResourceManager.GetString("lblRulesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string lblSalary {
            get {
                return ResourceManager.GetString("lblSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanctions/Penalties.
        /// </summary>
        public static string lblSanctionsPenalties {
            get {
                return ResourceManager.GetString("lblSanctionsPenalties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string lblSearch {
            get {
                return ResourceManager.GetString("lblSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string lblSection {
            get {
                return ResourceManager.GetString("lblSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string lblSelect {
            get {
                return ResourceManager.GetString("lblSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Leave.
        /// </summary>
        public static string lblSelectLeave {
            get {
                return ResourceManager.GetString("lblSelectLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string lblSend {
            get {
                return ResourceManager.GetString("lblSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services Provided to Customers.
        /// </summary>
        public static string lblServicesProvidedtoCustomers {
            get {
                return ResourceManager.GetString("lblServicesProvidedtoCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharing and Taking Responsibility.
        /// </summary>
        public static string lblSharingandTakingResponsibility {
            get {
                return ResourceManager.GetString("lblSharingandTakingResponsibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Leave.
        /// </summary>
        public static string lblShortLeave {
            get {
                return ResourceManager.GetString("lblShortLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Leave Request.
        /// </summary>
        public static string lblShortLeaveRequest {
            get {
                return ResourceManager.GetString("lblShortLeaveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        public static string lblShowAll {
            get {
                return ResourceManager.GetString("lblShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        public static string lblSignature {
            get {
                return ResourceManager.GetString("lblSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string lblSignOut {
            get {
                return ResourceManager.GetString("lblSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string lblSite {
            get {
                return ResourceManager.GetString("lblSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Status (Arabic).
        /// </summary>
        public static string lblSocialStatusArabic {
            get {
                return ResourceManager.GetString("lblSocialStatusArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Status (Arabic).
        /// </summary>
        public static string lblSocialStatusArb {
            get {
                return ResourceManager.GetString("lblSocialStatusArb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Status (English).
        /// </summary>
        public static string lblSocialStatusEng {
            get {
                return ResourceManager.GetString("lblSocialStatusEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Status (English).
        /// </summary>
        public static string lblSocialStatusEnglish {
            get {
                return ResourceManager.GetString("lblSocialStatusEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string lblStartDate {
            get {
                return ResourceManager.GetString("lblStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time/From.
        /// </summary>
        public static string lblStartTime {
            get {
                return ResourceManager.GetString("lblStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string lblSubject {
            get {
                return ResourceManager.GetString("lblSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisory skills.
        /// </summary>
        public static string lblSupervisoryskills {
            get {
                return ResourceManager.GetString("lblSupervisoryskills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taken Leave.
        /// </summary>
        public static string lblTakenLeave {
            get {
                return ResourceManager.GetString("lblTakenLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Description.
        /// </summary>
        public static string lblTheDescription {
            get {
                return ResourceManager.GetString("lblTheDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Level of Excellence and Exclusivity.
        /// </summary>
        public static string lblTheLevelofExcellenceandExclusivity {
            get {
                return ResourceManager.GetString("lblTheLevelofExcellenceandExclusivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string lblTime {
            get {
                return ResourceManager.GetString("lblTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time and Speed of Work.
        /// </summary>
        public static string lblTimeandSpeedofWork {
            get {
                return ResourceManager.GetString("lblTimeandSpeedofWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string lblTo {
            get {
                return ResourceManager.GetString("lblTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string lblTotal {
            get {
                return ResourceManager.GetString("lblTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Password.
        /// </summary>
        public static string lblUpdatePassword {
            get {
                return ResourceManager.GetString("lblUpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Expiry Date.
        /// </summary>
        public static string lblVisaExpiryDate {
            get {
                return ResourceManager.GetString("lblVisaExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Issue Date.
        /// </summary>
        public static string lblVisaIssueDate {
            get {
                return ResourceManager.GetString("lblVisaIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Release Date.
        /// </summary>
        public static string lblVisaReleaseDate {
            get {
                return ResourceManager.GetString("lblVisaReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsorship.
        /// </summary>
        public static string lblVisaSponsorship {
            get {
                return ResourceManager.GetString("lblVisaSponsorship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment not found.
        /// </summary>
        public static string MsgAttachmentNotFound {
            get {
                return ResourceManager.GetString("MsgAttachmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Near to expire document .
        /// </summary>
        public static string nearToExpireModalHeader {
            get {
                return ResourceManager.GetString("nearToExpireModalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of hours cannot be zero.
        /// </summary>
        public static string numberOfHourCannotBeZero {
            get {
                return ResourceManager.GetString("numberOfHourCannotBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string phEmail {
            get {
                return ResourceManager.GetString("phEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Number.
        /// </summary>
        public static string phEmployeeNumber {
            get {
                return ResourceManager.GetString("phEmployeeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string phPassword {
            get {
                return ResourceManager.GetString("phPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested day(s) should be less than or equal to available balance.
        /// </summary>
        public static string requesteddaysshouldbelessthanorequaltoavailablebalance {
            get {
                return ResourceManager.GetString("requesteddaysshouldbelessthanorequaltoavailablebalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested hour(s) should be less than or equal to available balance.
        /// </summary>
        public static string requestedhoursshouldbelessthanorequaltoavailablebalance {
            get {
                return ResourceManager.GetString("requestedhoursshouldbelessthanorequaltoavailablebalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date can not be greater than end date.
        /// </summary>
        public static string startdatecannotbegreaterthanenddate {
            get {
                return ResourceManager.GetString("startdatecannotbegreaterthanenddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date is required.
        /// </summary>
        public static string startdateisrequired {
            get {
                return ResourceManager.GetString("startdateisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time can not be greater than end time.
        /// </summary>
        public static string starttimecannotbegreaterthanendtime {
            get {
                return ResourceManager.GetString("starttimecannotbegreaterthanendtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational Document.
        /// </summary>
        public static string tabEducationalDocument {
            get {
                return ResourceManager.GetString("tabEducationalDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Document.
        /// </summary>
        public static string tabPersonalDocument {
            get {
                return ResourceManager.GetString("tabPersonalDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Info.
        /// </summary>
        public static string tabPersonalInfo {
            get {
                return ResourceManager.GetString("tabPersonalInfo", resourceCulture);
            }
        }
    }
}
