//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjectUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp.App_GlobalResources.ProjectUI", typeof(ProjectUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string lblAbout {
            get {
                return ResourceManager.GetString("lblAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string lblAboutUs {
            get {
                return ResourceManager.GetString("lblAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string lblAddNew {
            get {
                return ResourceManager.GetString("lblAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Conditioning and Ventilation Contracting.
        /// </summary>
        public static string lblAirConditionAndVentilationContacting {
            get {
                return ResourceManager.GetString("lblAirConditionAndVentilationContacting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval.
        /// </summary>
        public static string lblApproval {
            get {
                return ResourceManager.GetString("lblApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By.
        /// </summary>
        public static string lblApprovedBy {
            get {
                return ResourceManager.GetString("lblApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        public static string lblAssign {
            get {
                return ResourceManager.GetString("lblAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Date.
        /// </summary>
        public static string lblAssignDate {
            get {
                return ResourceManager.GetString("lblAssignDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned.
        /// </summary>
        public static string lblAssigned {
            get {
                return ResourceManager.GetString("lblAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Employee(s).
        /// </summary>
        public static string lblAssignedEmployees {
            get {
                return ResourceManager.GetString("lblAssignedEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Sub Section.
        /// </summary>
        public static string lblAssignedSubSection {
            get {
                return ResourceManager.GetString("lblAssignedSubSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign To.
        /// </summary>
        public static string lblAssignTo {
            get {
                return ResourceManager.GetString("lblAssignTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Employee(s).
        /// </summary>
        public static string lblAvailableEmployees {
            get {
                return ResourceManager.GetString("lblAvailableEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bathroom.
        /// </summary>
        public static string lblBathroom {
            get {
                return ResourceManager.GetString("lblBathroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string lblBranch {
            get {
                return ResourceManager.GetString("lblBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Status.
        /// </summary>
        public static string lblChangeStatus {
            get {
                return ResourceManager.GetString("lblChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string lblCity {
            get {
                return ResourceManager.GetString("lblCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string lblClient {
            get {
                return ResourceManager.GetString("lblClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Created Date.
        /// </summary>
        public static string lblClientCreatedDate {
            get {
                return ResourceManager.GetString("lblClientCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Details.
        /// </summary>
        public static string lblClientDetails {
            get {
                return ResourceManager.GetString("lblClientDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Document Information.
        /// </summary>
        public static string lblClientDocumentInformation {
            get {
                return ResourceManager.GetString("lblClientDocumentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Info.
        /// </summary>
        public static string lblClientInformation {
            get {
                return ResourceManager.GetString("lblClientInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client List.
        /// </summary>
        public static string lblClientList {
            get {
                return ResourceManager.GetString("lblClientList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Meeting And Contractors.
        /// </summary>
        public static string lblClientMeetingAndContractors {
            get {
                return ResourceManager.GetString("lblClientMeetingAndContractors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Meeting Information.
        /// </summary>
        public static string lblClientMeetingInformation {
            get {
                return ResourceManager.GetString("lblClientMeetingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name.
        /// </summary>
        public static string lblClientName {
            get {
                return ResourceManager.GetString("lblClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Project Information.
        /// </summary>
        public static string lblClientProjectInformation {
            get {
                return ResourceManager.GetString("lblClientProjectInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string lblClients {
            get {
                return ResourceManager.GetString("lblClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon...!.
        /// </summary>
        public static string lblComingSoon {
            get {
                return ResourceManager.GetString("lblComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string lblComplete {
            get {
                return ResourceManager.GetString("lblComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion Date.
        /// </summary>
        public static string lblCompletionDate {
            get {
                return ResourceManager.GetString("lblCompletionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concern Person.
        /// </summary>
        public static string lblConcernPerson {
            get {
                return ResourceManager.GetString("lblConcernPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction Months.
        /// </summary>
        public static string lblConstructionMonths {
            get {
                return ResourceManager.GetString("lblConstructionMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string lblContact {
            get {
                return ResourceManager.GetString("lblContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string lblContactUs {
            get {
                return ResourceManager.GetString("lblContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor.
        /// </summary>
        public static string lblContractor {
            get {
                return ResourceManager.GetString("lblContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor Details.
        /// </summary>
        public static string lblContractorDetails {
            get {
                return ResourceManager.GetString("lblContractorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor Info.
        /// </summary>
        public static string lblContractorInformation {
            get {
                return ResourceManager.GetString("lblContractorInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor List.
        /// </summary>
        public static string lblContractorList {
            get {
                return ResourceManager.GetString("lblContractorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string lblCost {
            get {
                return ResourceManager.GetString("lblCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string lblCreatedBy {
            get {
                return ResourceManager.GetString("lblCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Section Report.
        /// </summary>
        public static string lblDesignSectionReport {
            get {
                return ResourceManager.GetString("lblDesignSectionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string lblDetails {
            get {
                return ResourceManager.GetString("lblDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Information.
        /// </summary>
        public static string lblDocumentInformation {
            get {
                return ResourceManager.GetString("lblDocumentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string lblEmployeeName {
            get {
                return ResourceManager.GetString("lblEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineering Consultancy.
        /// </summary>
        public static string lblEngineeringConsultancy {
            get {
                return ResourceManager.GetString("lblEngineeringConsultancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire In.
        /// </summary>
        public static string lblExpiresIn {
            get {
                return ResourceManager.GetString("lblExpiresIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        public static string lblExpiryDate {
            get {
                return ResourceManager.GetString("lblExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Construction EndDate.
        /// </summary>
        public static string lblExtendedConstructionEndDate {
            get {
                return ResourceManager.GetString("lblExtendedConstructionEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Construction Months.
        /// </summary>
        public static string lblExtendedConstructionMonths {
            get {
                return ResourceManager.GetString("lblExtendedConstructionMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Construction StartDate.
        /// </summary>
        public static string lblExtendedConstructionStartDate {
            get {
                return ResourceManager.GetString("lblExtendedConstructionStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string lblFile {
            get {
                return ResourceManager.GetString("lblFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance.
        /// </summary>
        public static string lblFinance {
            get {
                return ResourceManager.GetString("lblFinance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial and Tax Consultancy.
        /// </summary>
        public static string lblFinancialAndTaxConsultancy {
            get {
                return ResourceManager.GetString("lblFinancialAndTaxConsultancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        public static string lblFloor {
            get {
                return ResourceManager.GetString("lblFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For.
        /// </summary>
        public static string lblFor {
            get {
                return ResourceManager.GetString("lblFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garage / Parking.
        /// </summary>
        public static string lblGarageParking {
            get {
                return ResourceManager.GetString("lblGarageParking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROUP BOARD OF DIRECTORS.
        /// </summary>
        public static string lblGroupOfBoardDirectors {
            get {
                return ResourceManager.GetString("lblGroupOfBoardDirectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall.
        /// </summary>
        public static string lblHall {
            get {
                return ResourceManager.GetString("lblHall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string lblHome {
            get {
                return ResourceManager.GetString("lblHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Resource(HR).
        /// </summary>
        public static string lblHumanResource {
            get {
                return ResourceManager.GetString("lblHumanResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string lblImage {
            get {
                return ResourceManager.GetString("lblImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Technology.
        /// </summary>
        public static string lblInformationTechnology {
            get {
                return ResourceManager.GetString("lblInformationTechnology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INMA.
        /// </summary>
        public static string lblINMA {
            get {
                return ResourceManager.GetString("lblINMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interior Design and Decoration.
        /// </summary>
        public static string lblInteriorDesignAndDecoration {
            get {
                return ResourceManager.GetString("lblInteriorDesignAndDecoration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue By Status.
        /// </summary>
        public static string lblIssueByStatus {
            get {
                return ResourceManager.GetString("lblIssueByStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date.
        /// </summary>
        public static string lblIssueDate {
            get {
                return ResourceManager.GetString("lblIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Details.
        /// </summary>
        public static string lblIssueDetails {
            get {
                return ResourceManager.GetString("lblIssueDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Information.
        /// </summary>
        public static string lblIssueInformation {
            get {
                return ResourceManager.GetString("lblIssueInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue List.
        /// </summary>
        public static string lblIssueList {
            get {
                return ResourceManager.GetString("lblIssueList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitchen.
        /// </summary>
        public static string lblKitchen {
            get {
                return ResourceManager.GetString("lblKitchen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string lblLocation {
            get {
                return ResourceManager.GetString("lblLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting.
        /// </summary>
        public static string lblMeeting {
            get {
                return ResourceManager.GetString("lblMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Date.
        /// </summary>
        public static string lblMeetingDate {
            get {
                return ResourceManager.GetString("lblMeetingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Details.
        /// </summary>
        public static string lblMeetingDetails {
            get {
                return ResourceManager.GetString("lblMeetingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting End.
        /// </summary>
        public static string lblMeetingEnd {
            get {
                return ResourceManager.GetString("lblMeetingEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting End Time.
        /// </summary>
        public static string lblMeetingEndTime {
            get {
                return ResourceManager.GetString("lblMeetingEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Information.
        /// </summary>
        public static string lblMeetingInformation {
            get {
                return ResourceManager.GetString("lblMeetingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting No.
        /// </summary>
        public static string lblMeetingNo {
            get {
                return ResourceManager.GetString("lblMeetingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Start Time.
        /// </summary>
        public static string lblMeetingStartTime {
            get {
                return ResourceManager.GetString("lblMeetingStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting time completed.
        /// </summary>
        public static string lblMeetingTimeCompleted {
            get {
                return ResourceManager.GetString("lblMeetingTimeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting With Engineer.
        /// </summary>
        public static string lblMeetingWithEngineer {
            get {
                return ResourceManager.GetString("lblMeetingWithEngineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string lblModule {
            get {
                return ResourceManager.GetString("lblModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mulk No.
        /// </summary>
        public static string lblMulkNo {
            get {
                return ResourceManager.GetString("lblMulkNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (Arabic).
        /// </summary>
        public static string lblNameArb {
            get {
                return ResourceManager.GetString("lblNameArb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (English).
        /// </summary>
        public static string lblNameEng {
            get {
                return ResourceManager.GetString("lblNameEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string lblNationality {
            get {
                return ResourceManager.GetString("lblNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Attachment.
        /// </summary>
        public static string lblNoAttachment {
            get {
                return ResourceManager.GetString("lblNoAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Expiry.
        /// </summary>
        public static string lblNoExpiry {
            get {
                return ResourceManager.GetString("lblNoExpiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Details.
        /// </summary>
        public static string lblNotificationDetails {
            get {
                return ResourceManager.GetString("lblNotificationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification List.
        /// </summary>
        public static string lblNotificationList {
            get {
                return ResourceManager.GetString("lblNotificationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old.
        /// </summary>
        public static string lblOld {
            get {
                return ResourceManager.GetString("lblOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Mission.
        /// </summary>
        public static string lblOurMission {
            get {
                return ResourceManager.GetString("lblOurMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Plan.
        /// </summary>
        public static string lblOurPlan {
            get {
                return ResourceManager.GetString("lblOurPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Vision.
        /// </summary>
        public static string lblOurVision {
            get {
                return ResourceManager.GetString("lblOurVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string lblOverview {
            get {
                return ResourceManager.GetString("lblOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Documents.
        /// </summary>
        public static string lblPersonalDocument {
            get {
                return ResourceManager.GetString("lblPersonalDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        public static string lblPersonalDocumentType {
            get {
                return ResourceManager.GetString("lblPersonalDocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Informations.
        /// </summary>
        public static string lblPersonalInformations {
            get {
                return ResourceManager.GetString("lblPersonalInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No.
        /// </summary>
        public static string lblPhone {
            get {
                return ResourceManager.GetString("lblPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string lblPhoneNumber {
            get {
                return ResourceManager.GetString("lblPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot No.
        /// </summary>
        public static string lblPlotNo {
            get {
                return ResourceManager.GetString("lblPlotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string lblPrice {
            get {
                return ResourceManager.GetString("lblPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession Name.
        /// </summary>
        public static string lblProfessionName {
            get {
                return ResourceManager.GetString("lblProfessionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string lblProgress {
            get {
                return ResourceManager.GetString("lblProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string lblProject {
            get {
                return ResourceManager.GetString("lblProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Area.
        /// </summary>
        public static string lblProjectArea {
            get {
                return ResourceManager.GetString("lblProjectArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project By Category.
        /// </summary>
        public static string lblProjectByCategory {
            get {
                return ResourceManager.GetString("lblProjectByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project By Status.
        /// </summary>
        public static string lblProjectByStatus {
            get {
                return ResourceManager.GetString("lblProjectByStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project By VIP Urgent.
        /// </summary>
        public static string lblProjectByVIPUrgent {
            get {
                return ResourceManager.GetString("lblProjectByVIPUrgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Category.
        /// </summary>
        public static string lblProjectCategory {
            get {
                return ResourceManager.GetString("lblProjectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Section.
        /// </summary>
        public static string lblProjectDesignSection {
            get {
                return ResourceManager.GetString("lblProjectDesignSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Details.
        /// </summary>
        public static string lblProjectDetails {
            get {
                return ResourceManager.GetString("lblProjectDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Document Information.
        /// </summary>
        public static string lblProjectDocumentInformation {
            get {
                return ResourceManager.GetString("lblProjectDocumentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Information.
        /// </summary>
        public static string lblProjectInformation {
            get {
                return ResourceManager.GetString("lblProjectInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project No.
        /// </summary>
        public static string lblProjectNo {
            get {
                return ResourceManager.GetString("lblProjectNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Status.
        /// </summary>
        public static string lblProjectStatus {
            get {
                return ResourceManager.GetString("lblProjectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervision Section.
        /// </summary>
        public static string lblProjectSupervisionSection {
            get {
                return ResourceManager.GetString("lblProjectSupervisionSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Section.
        /// </summary>
        public static string lblProjectTechnicalSection {
            get {
                return ResourceManager.GetString("lblProjectTechnicalSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Type.
        /// </summary>
        public static string lblProjectType {
            get {
                return ResourceManager.GetString("lblProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string lblReport {
            get {
                return ResourceManager.GetString("lblReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string lblReports {
            get {
                return ResourceManager.GetString("lblReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        public static string lblRoom {
            get {
                return ResourceManager.GetString("lblRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string lblSection {
            get {
                return ResourceManager.GetString("lblSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string lblServices {
            get {
                return ResourceManager.GetString("lblServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS List.
        /// </summary>
        public static string lblSmsList {
            get {
                return ResourceManager.GetString("lblSmsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Meeting.
        /// </summary>
        public static string lblStartMeeting {
            get {
                return ResourceManager.GetString("lblStartMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission.
        /// </summary>
        public static string lblSubmission {
            get {
                return ResourceManager.GetString("lblSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Section.
        /// </summary>
        public static string lblSubSection {
            get {
                return ResourceManager.GetString("lblSubSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string lblSummary {
            get {
                return ResourceManager.GetString("lblSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Report.
        /// </summary>
        public static string lblSummaryReport {
            get {
                return ResourceManager.GetString("lblSummaryReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string lblTeam {
            get {
                return ResourceManager.GetString("lblTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Section Report.
        /// </summary>
        public static string lblTechnicalSectionReport {
            get {
                return ResourceManager.GetString("lblTechnicalSectionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Clients.
        /// </summary>
        public static string lblTotalClients {
            get {
                return ResourceManager.GetString("lblTotalClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Contractors.
        /// </summary>
        public static string lblTotalContractors {
            get {
                return ResourceManager.GetString("lblTotalContractors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Meetings.
        /// </summary>
        public static string lblTotalMeetings {
            get {
                return ResourceManager.GetString("lblTotalMeetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Time.
        /// </summary>
        public static string lblTotalTime {
            get {
                return ResourceManager.GetString("lblTotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string lblTransfer {
            get {
                return ResourceManager.GetString("lblTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer To.
        /// </summary>
        public static string lblTransferTo {
            get {
                return ResourceManager.GetString("lblTransferTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string lblType {
            get {
                return ResourceManager.GetString("lblType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Supervision.
        /// </summary>
        public static string lblUpdateSupervision {
            get {
                return ResourceManager.GetString("lblUpdateSupervision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Document.
        /// </summary>
        public static string lblUploadDocument {
            get {
                return ResourceManager.GetString("lblUploadDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent.
        /// </summary>
        public static string lblUrgent {
            get {
                return ResourceManager.GetString("lblUrgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USEFUL LINKS.
        /// </summary>
        public static string lblUsefulLinks {
            get {
                return ResourceManager.GetString("lblUsefulLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIP.
        /// </summary>
        public static string lblVIP {
            get {
                return ResourceManager.GetString("lblVIP", resourceCulture);
            }
        }
    }
}
