//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjectUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp.App_GlobalResources.ProjectUI", typeof(ProjectUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string lblAddNew {
            get {
                return ResourceManager.GetString("lblAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string lblBranch {
            get {
                return ResourceManager.GetString("lblBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string lblCity {
            get {
                return ResourceManager.GetString("lblCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string lblClient {
            get {
                return ResourceManager.GetString("lblClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Created Date.
        /// </summary>
        public static string lblClientCreatedDate {
            get {
                return ResourceManager.GetString("lblClientCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Details.
        /// </summary>
        public static string lblClientDetails {
            get {
                return ResourceManager.GetString("lblClientDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Document Information.
        /// </summary>
        public static string lblClientDocumentInformation {
            get {
                return ResourceManager.GetString("lblClientDocumentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Info.
        /// </summary>
        public static string lblClientInformation {
            get {
                return ResourceManager.GetString("lblClientInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client List.
        /// </summary>
        public static string lblClientList {
            get {
                return ResourceManager.GetString("lblClientList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Meeting Information.
        /// </summary>
        public static string lblClientMeetingInformation {
            get {
                return ResourceManager.GetString("lblClientMeetingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name.
        /// </summary>
        public static string lblClientName {
            get {
                return ResourceManager.GetString("lblClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Project Information.
        /// </summary>
        public static string lblClientProjectInformation {
            get {
                return ResourceManager.GetString("lblClientProjectInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string lblClients {
            get {
                return ResourceManager.GetString("lblClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon...!.
        /// </summary>
        public static string lblComingSoon {
            get {
                return ResourceManager.GetString("lblComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string lblDetails {
            get {
                return ResourceManager.GetString("lblDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Information.
        /// </summary>
        public static string lblDocumentInformation {
            get {
                return ResourceManager.GetString("lblDocumentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire In.
        /// </summary>
        public static string lblExpiresIn {
            get {
                return ResourceManager.GetString("lblExpiresIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expity Date.
        /// </summary>
        public static string lblExpiryDate {
            get {
                return ResourceManager.GetString("lblExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string lblFile {
            get {
                return ResourceManager.GetString("lblFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string lblImage {
            get {
                return ResourceManager.GetString("lblImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date.
        /// </summary>
        public static string lblIssueDate {
            get {
                return ResourceManager.GetString("lblIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string lblLocation {
            get {
                return ResourceManager.GetString("lblLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (Arabic).
        /// </summary>
        public static string lblNameArb {
            get {
                return ResourceManager.GetString("lblNameArb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (English).
        /// </summary>
        public static string lblNameEng {
            get {
                return ResourceManager.GetString("lblNameEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string lblNationality {
            get {
                return ResourceManager.GetString("lblNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Documents.
        /// </summary>
        public static string lblPersonalDocument {
            get {
                return ResourceManager.GetString("lblPersonalDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        public static string lblPersonalDocumentType {
            get {
                return ResourceManager.GetString("lblPersonalDocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Informations.
        /// </summary>
        public static string lblPersonalInformations {
            get {
                return ResourceManager.GetString("lblPersonalInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No.
        /// </summary>
        public static string lblPhone {
            get {
                return ResourceManager.GetString("lblPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string lblProject {
            get {
                return ResourceManager.GetString("lblProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Details.
        /// </summary>
        public static string lblProjectDetails {
            get {
                return ResourceManager.GetString("lblProjectDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
    }
}
